name: Appointment Checker

on:
  schedule:
    - cron: '*/15 * * * *'  # Her 30 dakikada bir çalışır
  workflow_dispatch:        # Elle tetiklemek için

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu çek
        uses: actions/checkout@v3

      - name: Node.js kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Axios’u yükle
        run: npm install axios

      - name: Script’i çalıştır
        run: node check.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
